version: 2

updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "jonaharagon"
    reviewers:
      - "jonaharagon"
    labels:
      - "fix:github_actions"

  # Maintain dependencies for pipenv
  - package-ecosystem: "pip"
    directory: "/"
    ignore:
      - dependency-name: "mkdocs-material"
    schedule:
      interval: "daily"
    assignees:
      - "jonaharagon"
    reviewers:
      - "jonaharagon"
    labels:
      - "fix:python"
